config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :articles
  root 'welcome#index'
  resources :tasks
  root to: "home#index"
  resources :projects
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/projectx.rb
class Project < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
http_basic_authenticate_with name: "admin", password: "3132", except: [:index, :show]

def index
  @projects = Project.all
end

def show
  @project = Project.find(params[:id])
end

def new
  @project = Project.new
end

def edit
  @project = Project.find(params[:id])
end

def create
  @project = Project.new(project_params)

  if @project.save
    redirect_to @project
  else
    render 'new'
  end
end

def update
  @project = Project.find(params[:id])
  if @project.update(project_params)
    redirect_to @project
  else
    render 'edit'
  end
end

def destroy
  @project = Project.find(params[:id])
  @project.destroy

  redirect_to project_path
end

private
def project_params
  params.require(:project).permit(:name, :summary, :start_date, :end_date)
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "3132", except: [:index, :show]

    def index
      @tasks = Task.all
    end

    def show
      @task = Task.find(params[:id])
    end

    def new
      @task = Task.new
    end

    def edit
      @task = Task.find(params[:id])
    end

    def create
      @task = Task.new(task_params)

      if @task.save
        redirect_to @task
      else
        render 'new'
      end
    end

    def update
      @task = Task.find(params[:id])
      if @task.update(task_params)
        redirect_to @task
      else
        render 'edit'
      end
    end

    def destroy
      @task = Task.find(params[:id])
      @task.destroy

      redirect_to tasks_path
    end

    private
    def task_params
      params.require(:task).permit(:title, :description, :status)
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {
        success: "alert-success",
        error: "alert-danger",
        danger: "alert-danger",
        alert: "alert-warning",
        notice: "alert-info",
    }[name.to_sym] || name
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <nav>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <%= link_to "Projects", projects_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add project", new_project_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Tasks", tasks_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add task", new_task_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li>
         <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link pull-xs-right" %>
      </li>
         <% else %>
      <li class="pull-right">
         <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="pull-right">
         <%= link_to "Sign up", new_user_registration_path, class: "nav-link"  %>
      </li>
      <% end %>
  </ul>
  </nav>
  <% flash.each do |name, message| %>
  <div class="alert <%=bootstrap_class_for(name) %>">
    <button class="close" data-dismiss="alert">6times</button>
    <%= message %>
  </div>
  <% end %>
    <div class="container">
      <%= yield %>
    </div>

  </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: @project, local: true do |form| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :summary %><br>
    <%= form.text_area :text  %>
  </div>
  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.text_area :title %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.text_area :title %>
  </div>


  <div class="form-group">
    <%= form.submit %>
  </div>
</form>
<% end %>

app/views/projects/edit.html.erb
<%= form_with(model: @project, local: true) do |form| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>


<h1>Edit project</h1>

<%= render 'form' %>
<%= link_to 'Add task', tasks_path %>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h3>Listing projects</h3>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Summary</th>
    <th scope="col">Start date</th>
    <th scope="col">End date</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.title %></td>
      <td><%= project.summary %></td>
      <td><%= project.start_date %></td>
      <td><%= project.end_date %></td>
      <td></td>
    </tr>
    <div class="btn-group" role="group" aria-label="Basic example">
      <button type="button" class="btn btn-secondary"><%= link_to 'Show', project_path(project) %></button>
      <button type="button" class="btn btn-secondary"><%= link_to 'Edit', edit_project_path(project) %></button>
      <button type="button" class="btn btn-secondary"><%= link_to 'Destroy', project_path(project),
                                            method: :delete,
                                            data: { confirm: 'Are you sure?' } %></button>
    </div>


  <% end %>
  </tbody>
</table>

<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary"><%= link_to 'New project', new_project_path %></button>
</div>

app/views/projects/new.html.erb
<%= form_with scope: :project, url: projects_path, local: true do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form' %>

<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @project.summary %>
</p>
<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>
<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true do |form| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
    <div class="form-group">
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>
    <div class="form-group">
      <%= form.label :description %><br>
      <%= form.text_area :text  %>
    </div>
    <div class="form-group">
      <%= form.label :status %><br>
      <%= form.text_field :text  %>
    </div>

    <%= form.submit %>
  </form>


<% end %>

app/views/tasks/edit.html.erb
<%= form_with(model: @task, local: true) do |form| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>


<h1>Edit task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h3>Listing tasks</h3>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Description</th>
    <th scope="col">Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

<% @tasks.each do |task| %>
    <tbody>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td></td>

    <td><div class="btn-group" role="group" aria-label="Basic example">
      <button type="button" class="btn btn-secondary"><%= link_to 'Show', task_path(task) %></button>
      <button type="button" class="btn btn-secondary"><%= link_to 'Edit', edit_task_path(task) %></button>
      <button type="button" class="btn btn-secondary"><%= link_to 'Destroy', task_path(task),
                                          method: :delete,
                                                                    data: { confirm: 'Are you sure?' } %></button>
    </div></td>
  </tr>
<% end %>
  </tbody>
</table>
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary"> <%= link_to 'New task', new_task_path %></button>
  <button type="button" class="btn btn-secondary"> <%= link_to 'Back', projects_path %></button>
</div>

app/views/tasks/new.html.erb
<%= form_with scope: :task, url: tasks_path, local: true do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form' %>

<% end %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/welcome/index.html.erb
<h4>Тут должен быть projects list. (в теории)</h4>